#!/usr/bin/env npx tsx
/**
 * CLI: convert between .persona and SillyTavern Character Card V2.
 *
 * Usage:
 *   # Export .persona → character card JSON
 *   npx tsx scripts/convert-character-card.ts export <persona.json> [--png] [-o output]
 *
 *   # Import character card → .persona-like JSON (preview, not a real import)
 *   npx tsx scripts/convert-character-card.ts import <card.json|card.png> [-o output]
 *
 * The export path requires a .persona package JSON (the file, not a
 * live database). It does a best-effort conversion without database
 * queries (no synthesis_only filtering — that requires the live store).
 *
 * The import path parses a V2 card and prints the claim/corpus breakdown;
 * it does not write to any database (use the HTTP route for that).
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { CharacterCardV2Schema } from '../plugins/bridge-sillytavern/src/character-card';
import { readCharaFromPng, writeCharaToPng, generateMinimalPng } from '../plugins/bridge-sillytavern/src/png';

function usage(): never {
  console.error(`
Usage:
  convert-character-card export <persona-package.json> [--png] [-o output]
  convert-character-card import <card.json|card.png> [-o output]

Export: reads a .persona package JSON file and converts it to a
Character Card V2 JSON (or PNG with --png).

Import: reads a Character Card V2 (JSON or PNG) and prints the
extracted fields. Use the HTTP API for actual database import.
`.trim());
  process.exit(1);
}

function parseArgs(args: string[]): {
  command: 'export' | 'import';
  inputFile: string;
  outputFile?: string;
  png: boolean;
} {
  if (args.length < 2) usage();
  const command = args[0] as 'export' | 'import';
  if (command !== 'export' && command !== 'import') usage();

  const inputFile = args[1]!;
  let outputFile: string | undefined;
  let png = false;

  for (let i = 2; i < args.length; i++) {
    if (args[i] === '--png') png = true;
    else if (args[i] === '-o' && i + 1 < args.length) {
      outputFile = args[++i];
    }
  }

  return { command, inputFile, outputFile, png };
}

function exportPersona(inputFile: string, outputFile?: string, png = false): void {
  const raw = readFileSync(resolve(inputFile), 'utf8');
  const pkg = JSON.parse(raw);

  if (pkg.format !== 'openmimic.persona') {
    console.error('Error: input is not an OpenMimic .persona package');
    process.exit(1);
  }

  // Build card from package fields directly (no live store)
  const claims = (pkg.claims ?? []).filter((c: { status: string }) => c.status === 'surviving');
  const corpus = pkg.corpus ?? [];
  const witnesses = pkg.witnesses ?? [];

  const descriptionLines = claims.map((c: { text: string; qualifiers?: string[] }) => {
    const q = c.qualifiers?.length ? `（限定：${c.qualifiers.join('；')}）` : '';
    return `- ${c.text}${q}`;
  });

  const mesExampleLines: string[] = [];
  for (const ci of corpus) {
    mesExampleLines.push('<START>');
    mesExampleLines.push(`{{char}}: ${ci.text}`);
  }

  const card = {
    spec: 'chara_card_v2' as const,
    spec_version: '2.0' as const,
    data: {
      name: pkg.subject?.displayName ?? 'Unknown',
      description: descriptionLines.join('\n') || pkg.subject?.displayName || '',
      personality: claims.slice(0, 3).map((c: { text: string }) => c.text).join('\n'),
      scenario: '',
      first_mes: corpus[0]?.text ?? '...嗯？你找我？',
      mes_example: mesExampleLines.join('\n'),
      creator_notes: [
        `Generated by OpenMimic CLI from .persona package.`,
        `Based on ${witnesses.length} witness(es). Exported at: ${pkg.exportedAt ?? new Date().toISOString()}`,
        '',
        'IMPORTANT: This card does NOT contain the original testimonies.',
        'Once outside OpenMimic, there is no output-side fact-checking or privacy protection.',
      ].join('\n'),
      system_prompt: `You are roleplaying as ${pkg.subject?.displayName ?? 'the subject'}, a persona reconstructed from third-party testimonies. This is a simulation, not the real person.`,
      post_history_instructions: 'Stay within the facts provided. If uncertain, say so in character.',
      alternate_greetings: [] as string[],
      tags: ['openmimic', 'testimony-based'],
      creator: 'OpenMimic',
      character_version: '0.0.1',
      extensions: {} as Record<string, unknown>,
    },
  };

  const json = JSON.stringify(card, null, 2);

  if (png) {
    const placeholder = generateMinimalPng();
    const pngBuf = writeCharaToPng(placeholder, json);
    const out = outputFile ?? inputFile.replace(/\.json$/i, '.png');
    writeFileSync(resolve(out), pngBuf);
    console.log(`Written PNG card to: ${out}`);
  } else {
    const out = outputFile ?? inputFile.replace(/\.persona(\.json)?$/i, '.card.json');
    writeFileSync(resolve(out), json, 'utf8');
    console.log(`Written JSON card to: ${out}`);
  }
}

function importCard(inputFile: string, outputFile?: string): void {
  const filePath = resolve(inputFile);
  const raw = readFileSync(filePath);

  let cardData: unknown;
  if (inputFile.toLowerCase().endsWith('.png')) {
    cardData = readCharaFromPng(raw);
    if (!cardData) {
      console.error('Error: PNG does not contain a chara tEXt chunk');
      process.exit(1);
    }
  } else {
    cardData = JSON.parse(raw.toString('utf8'));
  }

  const card = CharacterCardV2Schema.parse(cardData);
  const { data } = card;

  console.log(`Name: ${data.name}`);
  console.log(`Description length: ${data.description.length} chars`);
  console.log(`Personality length: ${data.personality.length} chars`);
  console.log(`Scenario: ${data.scenario || '(empty)'}`);
  console.log(`First message: ${data.first_mes.slice(0, 80)}${data.first_mes.length > 80 ? '...' : ''}`);
  console.log(`Example messages: ${data.mes_example.length} chars`);
  console.log(`Creator: ${data.creator || '(none)'}`);
  console.log(`Tags: ${data.tags.join(', ') || '(none)'}`);
  console.log(`Has openmimic extension: ${!!data.extensions?.openmimic}`);
  console.log(`Alternate greetings: ${data.alternate_greetings.length}`);

  if (outputFile) {
    writeFileSync(resolve(outputFile), JSON.stringify(card, null, 2), 'utf8');
    console.log(`Written parsed card to: ${outputFile}`);
  }
}

// Main
const args = process.argv.slice(2);
const parsed = parseArgs(args);

if (parsed.command === 'export') {
  exportPersona(parsed.inputFile, parsed.outputFile, parsed.png);
} else {
  importCard(parsed.inputFile, parsed.outputFile);
}
